version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./local/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: services/web
    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/app
    environment:
      - PROJECT_ID=mython
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  nginx:
    build: services/nginx
    ports:
      - 80
      - 443
    depends_on:
      - db
      - web
